name: Playwright CI

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci
        working-directory: shopsmart-playwright

      - name: Install browsers
        run: npx playwright install --with-deps
        working-directory: shopsmart-playwright

      - name: Run tests
        run: npx playwright test
        working-directory: shopsmart-playwright

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: shopsmart-playwright/playwright-report
