name: Robot Framework Tests

on:
  push:
  pull_request:

jobs:
  robot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 'latest'

      - name: Run Robot tests (headless)
        run: |
          robot --outputdir reports tests

      - name: Upload Robot reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-reports
          path: reports/**
