name: Project 2 – Newman API Tests

on:
  push:
    paths:
      - 'api-quality-checks/**'
      - 'project-2-api-quality-checks/**'
  pull_request:
    paths:
      - 'api-quality-checks/**'
      - 'project-2-api-quality-checks/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect project directory
        id: detect
        run: |
          if [ -d project-2-api-quality-checks ]; then echo "dir=project-2-api-quality-checks" >> $GITHUB_OUTPUT;
          elif [ -d api-quality-checks ]; then echo "dir=api-quality-checks" >> $GITHUB_OUTPUT;
          else echo "API project folder not found"; exit 1; fi

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & run Newman
        run: |
          cd "${{ steps.detect.outputs.dir }}"
          npm install
          npm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: ${{ steps.detect.outputs.dir }}/reports/report.html
